# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: gersang_db
      POSTGRES_PASSWORD: gersang_db
      POSTGRES_DB: gersang_db_dev
      PGDATA: /var/lib/postgresql/data/gersang_db/
    volumes:
    - ./db:/var/lib/postgresql/data
    ports:
    - 5432:5432