# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: gersang_db
      POSTGRES_PASSWORD: gersang_db
      POSTGRES_DB: gersang_db_dev
      PGDATA: /var/lib/postgresql/data/gersang_db/
    volumes:
    - ./db:/var/lib/postgresql/data
    ports:
    - 5432:5432
  web:
    build: .
    working_dir: /app
    command: [
      "sh",
      "-c",
      # use seeds
      "mix deps.get && mix ecto.reset && mix phx.server"
      # use dump
      # "mix deps.get && mix ecto.drop && mix ecto.create && mix ecto.load && mix phx.server"
    ] # compile elm, run migrations and fire up phoenix
    volumes:
      - .:/app
    ports: 
    - 4000:4000
    depends_on:
      - db 